import { columns } from "@/components/public-topics-columns";
import PublicTopicsTable from "@/components/pulbic-topics-table";
import { TopicL1 } from "@/components/topic-preview";
import api from "@/util/interceptor";
import { useEffect, useState } from "react";
import Loading from "@/components/loading";
import { userTopicColumns } from "@/components/user-topics-columns";

function AllTopicsPage() {
  const [loading, setLoading] = useState(false);
  const [publicTopics, setPublicTopics] = useState<Array<TopicL1>>([]);
  const [userTopics, setUserTopics] = useState<Array<TopicL1>>([]);
  useEffect(() => {
    const fetchTopics = async () => {
      try {
        const res = await api.get("/topic");
        setPublicTopics(res.data.public_topics);
        setUserTopics(res.data.user_topics);
      } catch (err) {
        console.log(err);
      } finally {
        setLoading(false);
      }
    };
    setLoading(true);
    fetchTopics();
  }, []);

  if (loading) {
    return <Loading />;
  }

  return (
    <div className="h-screen font-custom">
      {/* Generated Topics Section */}
      <section className="p-2 mx-auto mt-2 md:w-[calc(100vw-16rem)] max-w-4xl">
        <div className="text-h1 mb-1">Generated By You</div>
        <PublicTopicsTable
          data={userTopics}
          columns={userTopicColumns}
        />
      </section>

      {/* Discover section */}
      <section className="p-2 mt-2 mx-auto md:w-[calc(100vw-16rem)] max-w-4xl">
        <div className="text-h1 mb-1">Discover More</div>
        <PublicTopicsTable data={publicTopics} columns={columns} />
      </section>
    </div>
  );
}

export default AllTopicsPage;
